In [1]:
# California datasets from sklearn

from sklearn import datasets

california = datasets.fetch_california_housing(data_home='./data/california_housing')

In [19]:
X = california.data
# Shape: (20640, 8) -> 20640 份資料, 每份資料有 8 個維度的提示 (例如人口)
print(X.shape)
print(X[::2].shape)
print(X[:2, ])
print(X[:2, [0, 3, 5]])
print(X[:2, [True, False, True, False, True, False, False, False]])

# print(california.data)

(20640, 8)
(10320, 8)
[[ 8.32520000e+00  4.10000000e+01  6.98412698e+00  1.02380952e+00
   3.22000000e+02  2.55555556e+00  3.78800000e+01 -1.22230000e+02]
 [ 8.30140000e+00  2.10000000e+01  6.23813708e+00  9.71880492e-01
   2.40100000e+03  2.10984183e+00  3.78600000e+01 -1.22220000e+02]]
[[8.3252     1.02380952 2.55555556]
 [8.3014     0.97188049 2.10984183]]
[[   8.3252        6.98412698  322.        ]
 [   8.3014        6.23813708 2401.        ]]


In [30]:
import numpy as np
X = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5, 9])
print(X[X <= 2])
print(np.mean(X))
print(np.std(X))

[1 1 2]
4.416666666666667
2.5644470922381863


In [28]:
X = np.array([[1, 2], [3, 4]])
X_inv = np.linalg.inv(X)
print(X)
print(X_inv)
print(X @ X_inv)  # Should be close to identity matrix

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [33]:
import torch
X = torch.Tensor(california.data[:, :6])
y = torch.Tensor(california.target)

print(X[0])
print(y[0])
print(y.shape)

tensor([  8.3252,  41.0000,   6.9841,   1.0238, 322.0000,   2.5556])
tensor(4.5260)
torch.Size([20640])


In [ ]:
L = torch.nn.Linear(2, 512)
x = torch.Tensor([8, 6])
y_pred = L(x)
print(y_pred.shape)

torch.Size([512])


In [45]:
import torch

class LinearRegression(torch.nn.Module):
    def __init__(self, input_size, output_size):
        super(LinearRegression, self).__init__()
        self.linear = torch.nn.Linear(input_size, 512)
        self.output = torch.nn.Linear(512, output_size)
    def forward(self, x):
        out = self.output(self.linear(x))
        return out


# linear = torch.nn.Linear(6, 1)
# print(linear.weight)
# print(linear.bias)
# x = torch.Tensor([1, 0, 0, 0, 0, 0])
# print(linear(x))

In [ ]:
criterion = torch.nn.MSELoss()
print(criterion(torch.tensor([1., 0]), torch.tensor([9., 1])))
# torch.mean((y_pred - y)**2)

tensor(32.5000)


In [ ]:
# Deploy linear algorithm by torch

input_size = 6
output_size = 1
model = LinearRegression(input_size, output_size)

criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-9)

for epoch in range(10):
    y_pred = model(X)
    loss = criterion(y_pred, y)
    print(epoch, loss.item())

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

0 11480.6796875
1 7428.09326171875
2 2342.575439453125
3 13.402742385864258


KeyboardInterrupt: 

In [34]:
y_pred = model(X)
for p, gt in zip(y_pred, y):
    print(p.item(), gt.item())


3.8418760299682617 4.526000022888184
0.98442143201828 3.5850000381469727
5.4076313972473145 3.5209999084472656
5.246996879577637 3.4130001068115234
5.802370071411133 3.421999931335449
5.487607955932617 2.697000026702881
5.367752552032471 2.992000102996826
5.49674129486084 2.4140000343322754
4.545604228973389 2.2669999599456787
5.211827754974365 2.6110000610351562
5.643024921417236 2.815000057220459
5.299643516540527 2.4179999828338623
5.556799411773682 2.134999990463257
5.672515392303467 1.9129999876022339
5.603178977966309 1.5920000076293945
5.427225112915039 1.399999976158142
5.85753870010376 1.524999976158142
5.671998977661133 1.5549999475479126
5.639364242553711 1.5870000123977661
5.814380168914795 1.628999948501587
4.757646083831787 1.475000023841858
4.678020477294922 1.5980000495910645
5.880886077880859 1.1390000581741333
5.774313449859619 0.996999979019165
5.679596900939941 1.3259999752044678
4.615396499633789 1.0750000476837158
5.395336151123047 0.9380000233650208
5.66424608230